### ISSUE TITLE
SIngle Cell

### ISSUE THREAD

**Issue by ashokpatowary** [hemberg-lab/MicroExonator#12]
Hi @geparada 

Thanks for this wonderful tool. I am trying to use MicroExonator on my long read single cell RNA seq data. I am having few very basic queries regarding this. Do I need to generated a pseudo bulk cell file for each cell type? Also do I need to run the Discovery and Quantification step or directly jumped into the Single Cell Analysis step? Finally, do we need to provide the fastq file for each celltype or we can provide the bam/sam file also.

**Comment by geparada** [comment]
Hey there,

We just published MicroExonator online last week! Thus now I am planning to attend the GitHub inquiries more actively. Moreover, I have worked a lot to improve the documentation of the single-cell module. I will try to update the online modification as soon as possible, but for the moment I have a document that I can share with you where these features are more deeply explained.

Please get in touch by email if you are still interested to get more information,
Best,
Guillermo
