### ISSUE TITLE
missing input file in Get_data.smk 

### ISSUE THREAD

**Issue by hypaik** [hemberg-lab/MicroExonator#27]
Hi, I'm trying to use this code for my research.  
It looks very promising. 

Now, I'm trying to use MicroExonator for the downloaded local files.
But it spits out an error and I can't figure it out.

Here is my config.yaml
$ cat config.yaml 
Genome_fasta : /blues/ngs/~~/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa
Gene_anontation_bed12 : /home/~~MicroExonator2/MicroExonator/gencode_vm25.bed12
GT_AG_U2_5 : /home/~~MicroExonator2/MicroExonator/PWM/Mouse/mm10_GT_AG_U2_5.good.matrix
GT_AG_U2_3 : /home/~~/MicroExonator2/MicroExonator/PWM/Mouse/mm10_GT_AG_U2_3.good.matrix
conservation_bigwig : /home/~~/MicroExonator/mm10.60way.phastCons.bw
working_directory : /home/~~/MicroExonator2/MicroExonator
ME_len : 30
Optimize_hard_drive : T
min_number_files_detected : 2
paired_samples: /home/~~/MicroExonator2/MicroExonator/local_samplePairs.tsv

My input file for local_samples.tsv is here:
path    sample
/blues/ngs/data/~~~/SRR9623780_1.fastq.gz   Murine_cortex:SRP212708A1
/blues/ngs/data/~~~/SRR9623780_2.fastq.gz   Murine_cortex:SRP212708A2
/blues/ngs/data/~~~/SRR9623802_1.fastq.gz   Murine_cortex:SRP212708B1
/blues/ngs/data/~~~/SRR9623802_2.fastq.gz   Murine_cortex:SRP212708B2
/blues/ngs/data/~~~/SRR9623803_1.fastq.gz   Murine_cortex:SRP212708C1
/blues/ngs/data/~~~/SRR9623803_2.fastq.gz   Murine_cortex:SRP212708C2

My file for the paired_samples is here:
Murine_cortex:SRP212708A1   Murine_cortex:SRP212708A2
Murine_cortex:SRP212708B1   Murine_cortex:SRP212708B2
Murine_cortex:SRP212708C1   Murine_cortex:SRP212708C2

When I run the code like this:
$ snakemake -s MicroExonator.smk --cluster-config cluster.json --cluster "sbatch --cpus-per-task {cluster.cpus} -p {cluster.p} --output {cluster.output} --error {cluster.error} --mem {cluster.mem}" --use-conda -k  -j 1

I only found the error message like this:
Building DAG of jobs...
MissingInputException in line 16 of /home/hyojung/srcGit/MicroExonator2/MicroExonator/rules/Get_data.smk:
Missing input files for rule download_fastq:
download/round2/Murine_cortex:SRP212708A2.download.sh

In the download folder there is no sub-folder named 'round2', but "Murine_cortex:SRP212708A2.download.sh" is exist. 
I can't understand why.

Thank you.

Regards,
Hanna

**Comment by geparada** [comment]
Hello Hanna,

Thanks for reporting this bug. I think this is an issue with the `Optimize_hard_drive : T` setting. This option is valuable when you have a lot of samples. For now, you could just try to turn it off by deleting the line or setting this to F. I will fix the bug relating to this option over the coming days, but in your case, I would not recommend this option unless you have a longer list of files you want to analyse or very limited hard drive space. 

Thanks!
Guillermo

**Comment by hypaik** [comment]
Thank you for your prompt response.
I followed your suggestion. The problem solved, so there is no error message for this reason.
Also it sounds good that you will fix this bug in near future.
