### ISSUE TITLE
error 'min_number_files_detected'

### ISSUE THREAD

**Issue by binasu** [hemberg-lab/MicroExonator#5]
Hi,

I'm excited to be using this new tool!

I've made a config.yaml file:

Genome_fasta : ~/MicroExonator/c_elegans.PRJNA13758.WS276.genomic.fa
Gene_anontation_bed12 : ~/MicroExonator/Caenorhabditis_elegans.WBcel235.bed12
GT_AG_U2_5 : NA
GT_AG_U2_3 : NA
conservation_bigwig : ~/MicroExonator/ce11.phyloP26way.bw  
working_directory : ~/MicroExonator/
ME_DB : ~/MicroExonator/Cel
ME_len : 27
Optimize_hard_drive : T

And a design.tsv file

path | sample
-- | --
/scratch/xx.fastq | xx
/scratch/yy.fastq | yy

And then did a dry-run:
snakemake -s MicroExonator.skm  --cluster-config config.yaml --use-conda -k -np

But I'm getting the error: 

KeyError in line 106 of /gpfs/fs1/home/MicroExonator/rules/Round2_post_processing.skm:
'min_number_files_detected'
  File "/gpfs/fs1/MicroExonator/MicroExonator.skm", line 69, in <module>
  File "/gpfs/fs1/MicroExonator/rules/Round2_post_processing.skm", line 106, in <module>

Could you let me know how to fix this?

Thanks

**Comment by SamBryce-Smith** [comment]
Hi,

Not the author, but came across this problem too. Fortunately it's a simple fix, all you have to do is add 'min_number_files_detected' and a value to the config.yaml file in same format as for other options e.g.

> min_number_files_detected: x

where x can be an integer of the minimum number of samples of your choosing.

Hope that helps,
Sam

**Comment by binasu** [comment]
> Hi,
> 
> Not the author, but came across this problem too. Fortunately it's a simple fix, all you have to do is add 'min_number_files_detected' and a value to the config.yaml file in same format as for other options e.g.
> 
> > min_number_files_detected: x
> 
> where x can be an integer of the minimum number of samples of your choosing.
> 
> Hope that helps,
> Sam

Great! That was it, thank you! I didn't see this parameter in the outline of the config.yaml file

**Comment by geparada** [comment]
I have addressed this issue over the new documentation:

https://microexonator.readthedocs.io/en/latest/discovery_and_quantification.html

Thanks a lot!
