### ISSUE TITLE
Output rule Round2 Error: object 'min_number_files_detected' not found (easy fix)

### ISSUE THREAD

**Issue by SamBryce-Smith** [hemberg-lab/MicroExonator#7]
Hi,

Just reporting a small error that occurs with the *Output* rule (round2) when generating the html report. Received the following error message:

```
Quitting from lines 196-214 (final_filters2.Rmd)
Error in FUN(X[[i]], ...) : object 'min_number_files_detected' not found
```
Fortunately this was a simple fix. In *src/final_filters2.Rmd*, 'min_number_files_detected' is not defined from params in chunk 3:

```{r, echo=FALSE, eval=TRUE}

ME_table=params$ME_table
ME_coverage=params$ME_coverage
ME_matches_file=params$ME_matches_file

out_filtered_ME=params$out_filtered_ME
out_low_scored_ME=params$out_low_scored_ME
out_shorter_than_3_ME=params$out_shorter_than_3_ME


out_filtered_ME_cov = params$out_filtered_ME_cov

```

Defining the variable in chunk 3 eliminates the error message and the rest of the script runs without other errors.
```min_number_files_detected=params$min_number_files_detected```

Thanks,
Sam

**Comment by geparada** [comment]
Thanks for reporting this Sam!

This was actually meant to be defined from the configuration files. I just finished the full documentation of MicroExonator and you can see the description of this parameter as part of the `Minimal configuration`: https://microexonator.readthedocs.io/en/latest/discovery_and_quantification.html

Now that the documentation is up to date, please let me know if you have any other question.

Cheers,
Guille
